### ISSUE TITLE
Orthographic camera not working on sagittal and coronal orientation for certain DICOMs

### ISSUE THREAD

**Issue by wysoh** [FNNDSC/ami#158]
### Description
I'm trying some of the examples in your project with our own DICOM data, for most part it's working fine, but for certain DICOM files, the sagittal and coronal orientations are not rendering correctly. It only shows for some part near the end of each sides, the rest are just white screen. However, the axial orientation is working just fine.

#### Live Demo
We do not have a way to expose the DICOM files to the public, but here's a screenshot showing the problem. 
https://screencast.com/t/PiJhabIdqid
https://screencast.com/t/eZKvdHfbmN

If the actual DICOM files are needed to diagnose the problem, I will be more than happy to find a way.

### Browsers Affected
- [X] All
- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- AMI: v0.0.15
- THREEJS: r83

**Comment by wysoh** [comment]
Forgot the mention that the same DICOM files are working fine using Papaya. (https://github.com/rii-mango/Papaya/)

**Comment by NicolasRannou** [comment]
Hi @wysoh , it seems that the issue is just that the "intensityAuto" flag should be set to false:
`stackHelper.slice.intensityAuto = false;`

The fact that it works in "1 direction" means that everything is OK.

`stackHelper.slice.intensityAuto` reads the preferred window/level values from the current DICOM frame then applies it. It seem that you data was acquired "AXIAL" so window/level will be properly picked up for the AXIAL view. However we can not read the preferred window/level for CORONAL and SAGITTAL views.

Setting  `stackHelper.slice.intensityAuto = false;` will prevent AMI from trying to guess window/level and should work fine.

Please let me know if that helps!

**Comment by wysoh** [comment]
Yes, it's working fine after setting the flag. Thank you very much for your prompt response!
