### ISSUE TITLE
[suggestion] Hard Update to ES Modules

### ISSUE THREAD

**Issue by k1r0s** [FNNDSC/ami#231]
This library needs a hard refactor to allow other libraries to use it on web applications. Nowadays it relies on script tags directly on the HTML which isn't the proper way to do it.

Basically dependencies such as Threejs sould be bundled to the build output. Right now you've to set dependencies manually...

The goal is to **only** have to import ami.js through npm system after running `npm install --save ami.js`.

`import ami from "ami.js"`

It would be nice to use this standard http://exploringjs.com/es6/ch_modules.html. 

I can provide more information or help if needed.

Thanks for this awesome lib

**Comment by k1r0s** [comment]
the workaround is to set THREE as a global variable from your project: 

```javascript
window.THREE = require("three");
const ami = require("ami.js");
```

But I cannot guarantee that it would work properly..

**Comment by NicolasRannou** [comment]
Really happy to improve/refactor to improve it -

The problem with including `THREEJS` inside the build is that if a user has an external `THREEJS` scene then wants to add some of `AMI`'s stuff in it, the IDs of the meshes/geometries may collapse ending breaking the app.

If you have any suggestion on how we can fix this issue I'd be very happy - I wanted to include `THREEJS` in the lib before but did revert all changes because IDs of the AMI-based objects were conflicting with the IDs of the external THREEJS stuff.

But I'm sure there is a good workaround - just no time to look into it.
https://discourse.threejs.org/t/mix-modules-and-global-definitions/806

**Comment by NicolasRannou** [comment]
@k1r0s it is all fixed now with the new factory pattern for helpers, widgets, controls and cameras:
```
import * as THREE from 'three';

import {stackHelperFactory} from 'ami.js';

const StackHelper = stackHelperFactory(THREE);
const stackHelper = new StackHelper();
```

Please re-open if needed!
