### ISSUE TITLE
[Question] Empty voxels and useless voxels for .DICOM format images

### ISSUE THREAD

**Issue by Humphrey8** [FNNDSC/ami#233]
How to deal with empty or useless voxels in .dicom format images in AMI? Can you talk about it in detail? Or can you give me your reference?  I want to go deeper to understand the handling mechanism. Thanku you very much . Looking forward to your reply

**Comment by NicolasRannou** [comment]
Hi @Humphrey8, I do not understand your question. What do you mean empty or useless voxels? There is no such thing as far as I know.

**Comment by Humphrey8** [comment]
Empty voxels I refer to are voxels whose voxel values are not in the display range and do not contribute to the resulting final image. How do you deal with these voxels? My expression may not be clear before

**Comment by DIeHarke** [comment]
I think what he wants is to mask out voxels, whose intensity values are below a given threshold. When rendering the texture of the image slice he wants all those masked out voxels to be transparent.

If this is what you want, you could either achieve this by defining your own LUT, where the opacity would be 0 for the voxels under your defined threshold. Or you utilize the "Label Maps" feature where your mask would be defined as a label. Then during texture rendering instead of adding a label color you would set the alpha to be 0.

**Comment by NicolasRannou** [comment]
Yes @DIeHarke that is one approach. However I would just add 2 new uniforms in the shader and just add something like:
https://github.com/FNNDSC/ami/blob/dev/src/shaders/shaders.data.fragment.js#L84
```
if ( normalizedIntensity < uLowerThreshold ||
      normalizedIntensity > uUpperThreshold) {
  discard;
}
```

Does it make sense?

**Comment by NicolasRannou** [comment]
Closing in favor of #80
