### ISSUE TITLE
Support for oblique MPR

### ISSUE THREAD

**Issue by diaztula** [FNNDSC/ami#287]
Dear Nicolas,

I'm using AMI and it's working very well. I'm just wondering if AMI supports oblique MPR.

Cheers!

**Comment by NicolasRannou** [comment]
Yes that should be working out of the box. However there is no "stack helper" for that so you may have to connect things manually:

https://fnndsc.github.io/ami/#geometries_slice

https://github.com/FNNDSC/ami/issues/161

Please re-open if you have more questions and do not hesitate to send PRs :)

**Comment by MuriloSchaefer** [comment]
Hi,

I'm going to use this tool to do the MPR too, I just have some questions:
Could I generate other series (sagittal and coronal) from the axial serie? generating the stack which could be rendered in a 2D plane?

Cheers

**Comment by diaztula** [comment]
Hello Murilo

I did not understand your question. In MPR we have only one view (axial, saggital, or coronal, but only one of them) and "reconstruct" the other 2 views. Let say you have a CT with slices in the axial direction, then with MPR you will be able to see the image from the the saggital and coronal perspectives as well.

Cheers

**Comment by MuriloSchaefer** [comment]
Hi diaztula,

Yes, that's not the point, I'll try to explain me better, sorry.
If you look at the this example: https://fnndsc.github.io/ami/#geometries_slice you can see that the images doesn't have a good quality, there's like a blur or something like that. 
My question is, this is because the number of images utilized, or the images itself, or even the algorithm utilized?

Thank you for the quick reply :)

**Comment by diaztula** [comment]
Hi Murilo

Now I see your point. I think that to some extent it has to do with the original image quality (resolution, distance between adjacent slices). If slices are more distant then the reconstruction will have less quality because some kind of interpolation is needed to fill in the gaps in the reconstructed images.

I'm not sure about this but I think that AMI uses a feature from THREEJS that do the interpolation itself by specifying the points of the viewing plane in 3D. This makes it easy to do oblique viewing quickly, but I do not now what algorithm it uses to do reconstruction.

Cheers!

**Comment by MuriloSchaefer** [comment]
I'll try to use it and see what I get.

I'll let you know about the results :)

Thanks for the help

**Comment by NicolasRannou** [comment]
Hi, the reason resolution is not optimal in some directions is because the spacing between each slice is about 1cm whereas the in-frame spacing is about (.2 x .2);

AMI does quadratic interpolation to get the pixel value.

Do you know some other methods/software that provide different results during MPR?

**Comment by MuriloSchaefer** [comment]
No, I couldn't do better. :)

Was just a thought about what could be happening.

Thanks,
