### ISSUE TITLE
2D Representation isn't working

### ISSUE THREAD

**Issue by PunkHaz4rd** [FNNDSC/ami#51]
Whenever I use a serie to make a 2D representation, following the example, I get almost half the serie that works, then the other half is just noise (like on old tvs).

[Here's the view for the images that don't compute](http://imgur.com/kIGkg4i)

I don't know where it comes from, as it works on the OSIRIX desktop viewer.

It's the same on the example where I load dicom files with those series.
Is there something I'm missing ?

Thanks.

**Comment by NicolasRannou** [comment]
Can you share the data with us by any chance?

The strange this is that half works..

Can you give a try to http://fnndsc.github.io/ami/#viewers_dicom2D as a test?

**Comment by PunkHaz4rd** [comment]
Yes, I used [this one](http://www.osirix-viewer.com/datasets/DATA/COLONIX.zip) from the OSIRIX samples, both on my code and the online example.
It's quite heavy.
As I just tried, it seems that with only 200 images from COLONIX, it works, so I guess it could be a memory problem (blobs being flushed and all).

**Comment by NicolasRannou** [comment]
Yes the problem is the following:

This dataset contains 512 x 512 x 889 = 233 046 016 voxels.

Currently AMI on passes the first 4096 * 4096 * 7 = 117 440 512 voxels to the shader.

That explains that roughly the first half looks fine and the second half doesn't.

The only reason for limiting the number of voxels was to make it working on a wider range of devices but it should be better handled. There is no perfect solutions and there are pros and cons for all:

* Pass all voxels -> requires high-end graphic card
* Pass only interesting packages of voxels -> can only look at the data in acquisition direction
* Create several stackHelpers for each data subset -> not sure how that will look like at intersection points

So I think the best solution really depends on what you want to achieve: 2D, 3D, which orientation, which target device, etc.

**Last thought is that `AMI could actually already handle this dataset`:**

To pass data to the shaders, it packs the voxel intensities into a [rgba] texture (8 bits per channel). This OSIRIX dataset is 16 bits grayscale, meaning that [rg] could contain 1 voxel intensity and [ba] another one.

This way we can pass 2 times more voxels to the shaders than we currently do.

That would be very to have that in AMI, if you are interested I can help you get through the code and point you to the right direction as I do not know when I'll be able to fix it.

**Comment by PunkHaz4rd** [comment]
My use of the library is pretty specific.

I want to only process CT scan in sagittal view and to be able to point probes.

To be honest, I don't understand everything about voxels. I would like to help but I don't think I'm able to.

Basically what could be implemented in AMI is a way to configure the way series are shown, to be able to tweak the graphics when instanciating the library ?

**Comment by NicolasRannou** [comment]
FYI - working on it, still got couple of issues to resolve

**Comment by PunkHaz4rd** [comment]
Awesome ! Thank you very much.

**Comment by NicolasRannou** [comment]
Note - it also seems that it tries to create too many textures.

**Comment by NicolasRannou** [comment]
FYI - some good progress but still more cleanup/testing to do:
![jul-20-2016 09-09-08](https://cloud.githubusercontent.com/assets/214063/16977998/d1c28f88-4e59-11e6-88f4-489d1d4a8151.gif)

**Comment by NicolasRannou** [comment]
Please give it a try at https://fnndsc.github.io/ami/#viewers_dicom2D and let us know if it works as expected!

(you might need to clean up your cache or try in an anonymous tab)

It is not on master yet but you can access it in the #dev branch -
Cheers!
