### ISSUE TITLE
Resolution of sagittal and coronal views

### ISSUE THREAD

**Issue by SevenSinS02** [FNNDSC/ami#98]
Hi @NicolasRannou ,

Is there a way to give a better resolution output for sagittal and coronal views?

**Comment by NicolasRannou** [comment]
Hi @SevenSinS02 -

There is not much we can do about right now. The resolution of the views that are not "acquisition direction" is lower because the spacing between slices is much bigger than the "in-plane" spacing.

Right now AMI just presents the images as it is, without any advanced image processing to improve the appearance.

The only thing we do is that we do some trilinear interpolation between the voxels to smooth results out.

To understand better the problem, just load your data in AMI and turn "OFF" the interpolation. You will see that the voxels are stretched in SAGITALL/CORONAL views because the spacing between spacing is big.

![screen shot 2017-02-06 at 10 36 03 am](https://cloud.githubusercontent.com/assets/214063/22641748/4af56a28-ec58-11e6-9fcf-cbe8367c3317.png)

![screen shot 2017-02-06 at 10 36 17 am](https://cloud.githubusercontent.com/assets/214063/22641766/54742dd2-ec58-11e6-90e2-046e34349f15.png)
